### ISSUE TITLE
Twitter Error

### ISSUE THREAD

**Issue by orhanxq0** [justinmerrell/Twitter-AutoPost#1]
Traceback (most recent call last):
  File "/home/mint/Downloads/Twitter-AutoPost/tweet.py", line 32, in <module>
    raise Exception(
Exception: Request returned an error: 403 {
  "title": "Unsupported Authentication",
  "detail": "Authenticating with Unknown is forbidden for this endpoint.  Supported authentication types are [OAuth 1.0a User Context, OAuth 2.0 User Context].",
  "type": "https://api.twitter.com/2/problems/unsupported-authentication",
  "status": 403
}

**Comment by justinmerrell** [comment]
Did you set up your credentials in a .env file?
