### ISSUE TITLE
Does this need a paid twitter developer account?

### ISSUE THREAD

**Issue by tkd-itsuki** [justinmerrell/Twitter-AutoPost#2]
I am just wondering since using twitter via api doesn't allow user to post anymore.

**Comment by justinmerrell** [comment]
No, you should be able to post to your account unless I was grandfathered in since I do not have a paid account. 

Also I do not see anything restrictions based on this https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api
